alias: Bedtime Scene Off
hide_entity: True
trigger:
  platform: state
  entity_id: input_boolean.bedtime_scene
  from: 'on'
  to: 'off'
action:
  - service: light.turn_off
    entity_id: light.stand_lamp_dimmer_2_level
  - service: light.turn_off
    entity_id: light.lifx_study
  - service: input_boolean.turn_off
    entity_id: input_boolean.fan_light
  - service: switch.turn_off
    entity_id: switch.woodstock_switch