alias: Front Door Video Capture
hide_entity: True
trigger: 
  platform: state
  entity_id: binary_sensor.multisensor_outside_front_door_motion
  from: 'off'
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.front_door_sensor_sensor
      state: 'off'
action:
  - service: shell_command.camera_capture_video