alias: Morning Routine Scene Off
hide_entity: True
trigger:
  platform: state
  entity_id: input_boolean.morning_scene
  from: 'on'
  to: 'off'
action:
  - service: media_player.media_stop
    entity_id: media_player.everywhere
  - service: switch.turn_off
    entity_id: switch.lucy_switch
- alias: 'Set Spotify Volume'
trigger:
    platform: state
    entity_id: input_number.spotify_volume
action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.spotify
      volume_level: '{{  states.input_number.spotify_volume.state  }}'
