alias: 'Set Everywhere Volume'
trigger:
    platform: state
    entity_id: input_number.announcements_volume
action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.everywhere
      volume_level: '{{ states.input_number.announcements_volume }}'