alias: Away
trigger:
  platform: state
  entity_id: group.phonetrackers
  to: 'not_home'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.home_status_dropdown
      option: Away