alias: Morning Home
hide_entity: True
trigger:
  platform: state
  entity_id: group.indoormotionsensors
  from: 'off'
  to: 'on'
condition:
  condition: and
  conditions: 
    - condition: time
      after: '06:00:00'
    - condition: time
      before: '11:00:00'
    - condition: state
      entity_id: group.phonetrackers
      state: 'home'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.home_status_dropdown
      option: Morning Home