alias: Sleeping
hide_entity: True
trigger:
  platform: state
  entity_id: group.indoormotionsensors
  from: 'on'
  to: 'off'
  for:
    minutes: 3
condition:
  condition: and
  conditions: 
    - condition: time
      after: '21:00:00'
    - condition: state
      entity_id: group.phonetrackers
      state: 'home'
    - condition: state
      entity_id: light.living_dimmer_1_level
      state: 'off'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.home_status_dropdown
      option: Sleeping