alias: Ruby Bed Time
hide_entity: True
trigger:
  - platform: time
    at: '19:00:00'
  - platform: state
    entity_id: input_boolean.ruby_bedtime
    from: 'off'
    to: 'on'
action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.everywhere
      volume_level: '{{ states.input_number.announcements_volume }}'
  - service: tts.google_say
    entity_id: media_player.everywhere
    data:
      message: 'Ruby its time for bed, go brush your teeth.'
  - service: input_boolean.turn_off
    entity_id: input_boolean.ruby_bedtime
