alias: Turn Fan On
hide_entity: True
trigger:
  platform: mqtt
  topic: ceiling_fan/on/set
  payload: 'true'
action:
  - service: shell_command.fan_med
  - service: mqtt.publish
    data:
      topic: "ceiling_fan/on/state"
      payload: "true"
  - service: mqtt.publish
    data:
      topic: "ceiling_fan/speed/state"
      payload: "medium"