alias: Standing Light Dimmer
hide_entity: True
trigger:
  - platform: state
    entity_id: input_boolean.rf_remote_3_c
action:
  - service: light.turn_off
    entity_id: light.stand_lamp_dimmer_1_level
