alias: Entrance Hall Motion Light
hide_entity: True
trigger:
  platform: state
  entity_id: binary_sensor.foyer_motion_sensor_14
  from: 'off'
  to: 'on'
condition:
  condition: and
  conditions: 
    - condition: numeric_state
      entity_id: sensor.outside_light_sensor_20
      below: 51
    - condition: state
      entity_id: input_boolean.auto_lights
      state: 'on'
action:
  - service: light.turn_on
    data: 
      entity_id: light.charlie_dimmable_13
      brightness: 40 # 0 to 255
  - service: light.turn_on
    data: 
      entity_id: light.living_dimmer_2_28
      brightness: 1 # 0 to 255
  - delay:
      minutes: 2
  - service: light.turn_off
    data:
      entity_id: light.charlie_dimmable_13
  - service: light.turn_off
    data:
      entity_id: light.living_dimmer_2_28