alias: Foyer Motion Light
hide_entity: True
trigger:
  platform: state
  entity_id: binary_sensor.foyer_motion_sensor_14
  from: 'off'
  to: 'on'
condition:
  condition: and
  conditions: 
    - condition: numeric_state
      entity_id: sensor.outside_light_sensor_20
      below: 51
    - condition: state
      entity_id: input_boolean.auto_lights
      state: 'on'   
action:
  - service: script.foyer_motion_light_standing_on
  - service: script.foyer_motion_light_dimmer2_on
