alias: Foyer Motion Light
hide_entity: True
trigger:
  platform: state
  entity_id: binary_sensor.multisensor_foyer_motion
  from: 'off'
  to: 'on'
condition:
  condition: and
  conditions: 
    - condition: numeric_state
      entity_id: sensor.multisensor_outside_front_door_lux
      below: 51
    - condition: state
      entity_id: input_boolean.auto_lights
      state: 'on'
    - condition: template
      value_template: "{{states('input_select.home_status_dropdown') == 'Sleeping'}}"
action:
  - service: script.foyer_motion_standing_lamp_dimmer2_on