alias: Front Door Light Motion
hide_entity: True
initial_state: False
trigger:
  - platform: state
    entity_id: binary_sensor.multisensor_outside_front_door_motion
    from: 'off'
    to: 'on'
condition:
  condition: and
  conditions: 
    - condition: numeric_state
      entity_id: sensor.multisensor_outside_front_door_lux
      below: 51
    - condition: state
      entity_id: input_boolean.auto_lights
      state: 'on'   
action:
  - service: script.foyer_motion_standing_lamp_dimmer2_on
