alias: Front Door Light Garage
hide_entity: True
initial_state: False
trigger:
  - platform: state
    entity_id: input_select.garage_status_dropdown
    to: 'Door Open'
  - platform: state
    entity_id: binary_sensor.front_door_sensor
    to: 'on'
condition:
  condition: and
  conditions: 
    - condition: numeric_state
      entity_id: sensor.multisensor_outside_front_door_lux
      below: 51
    - condition: state
      entity_id: input_boolean.auto_lights
      state: 'on'   
action:
  - service: script.front_door_light_on
