alias: Living Room Linked Dimmers Off
hide_entity: True
trigger:
  - platform: state
    entity_id: light.living_dimmer_1_level
    from: 'on'
    to: 'off'
condition:
  condition: and
  conditions: 
    - condition: state
      entity_id: input_boolean.auto_lights
      state: 'on'
action:
  - service: light.turn_off
    data: 
      entity_id: light.living_dimmer_2_level
  - service: shell_command.fan_light_off    