alias: Ruby Lifx Colour Next
hide_entity: True
trigger:
  platform: state
  entity_id: input_boolean.rf_remote_4_on
condition:
action:
  - service: light.lifx_set_state
    data_template:
      entity_id: light.lifx_ruby_room
      color_name: >
            {{['magenta','lime','red','teal','turquoise','violet','slateblue','orange','lightpink','hotpink','greenyellow','fuchsia','forestgreen','deepskyblue','deeppink','darkorange','cyan','aqua']|random}}
      transition: 2