alias: Garage Door Open
hide_entity: True
trigger:
  - platform: homeassistant
    event: start
  - platform: numeric_state
    entity_id: sensor.sn1_distance
    above: 130
    below: 280
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.garage_status_dropdown
      option: Door Closed No Car