alias: Delay automations on restart
hide_entity: True
trigger:
  platform: homeassistant
  event: start
action:
  - service: device_tracker.see
    data:
      dev_id: ettiennes_iphone
      location_name: 'home'
  - service: device_tracker.see
    data:
      dev_id: kkramers_iphone
      location_name: 'home'
  - delay:
      seconds: 20
  - service: automation.turn_on
    entity_id: automation.front_door_light_garage, automation.garage_light_on, automation.garage_light_off , automation.front_door_light_motion
