alias: Rf Remote Bauhn All On
hide_entity: True
trigger:
  platform: mqtt
  topic: "home/OpenMQTTGateway/433toMQTT"
  payload: "349144259"
action:
  - service: input_boolean.toggle
    entity_id: input_boolean.rf_remote_all_on