alias: Remote 2 B Off
hide_entity: True
trigger:
  platform: state
  entity_id: input_boolean.rf_remote_2_b
  from: 'on'
  to: 'off'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.morning_scene