alias: Rf Remote Bauhn 4 On
hide_entity: True
trigger:
  platform: mqtt
  topic: "home/OpenMQTTGateway/433toMQTT"
  payload: "349146830"
action:
  - service: input_boolean.toggle
    entity_id: input_boolean.rf_remote_4_on