alias: Rf Remote 1 On
hide_entity: True
trigger:
  platform: event
  event_type: pilight_received
  event_data:
    protocol: rc101
    id: 127784
    uuid: 0000-b8-27-eb-60df5f   
    state: 'on'
    unit: 0
    all:
action:
  - service: input_boolean.toggle
    entity_id: input_boolean.rf_remote_1_on