alias: Rf Remote Bauhn All Off
hide_entity: True
trigger:
  platform: mqtt
  topic: "home/OpenMQTTGateway/433toMQTT"
  payload: "349145291"
action:
  - service: input_boolean.toggle
    entity_id: input_boolean.rf_remote_all_off