alias: Rf Remote 3 A
hide_entity: True
trigger:
  platform: mqtt
  topic: "home/OpenMQTTGateway/433toMQTT"
  payload: "6402360"
action:
  - service: input_boolean.toggle
    entity_id: input_boolean.rf_remote_3_a