alias: Rf Remote 2 D
hide_entity: True
trigger:
  platform: mqtt
  topic: "home/OpenMQTTGateway/433toMQTT"
  payload: "2599025"
action:
  - service: input_boolean.toggle
    entity_id: input_boolean.rf_remote_2_d