alias: Rf Remote 3 C
hide_entity: True
trigger:
  platform: event
  event_type: pilight_received
  event_data:
    protocol: ev1527
    unitcode: 637244
    uuid: 0000-b8-27-eb-60df5f   
    state: 'closed'
action:
  - service: input_boolean.toggle
    entity_id: input_boolean.rf_remote_3_c