alias: Rf Remote Bauhn 1 On
hide_entity: True
trigger:
  platform: mqtt
  topic: "home/OpenMQTTGateway/433toMQTT"
  payload: "349147087"
action:
  - service: input_boolean.toggle
    entity_id: input_boolean.rf_remote_1_on