alias: RF Remote 2 A On
hide_entity: True
trigger:
  platform: state
  entity_id: input_boolean.rf_remote_2_a
  from: 'off'
  to: 'on'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.bedtime_scene