alias: Rf Remote Bauhn 2 On
hide_entity: True
trigger:
  platform: mqtt
  topic: "home/OpenMQTTGateway/433toMQTT"
  payload: "349146056"
action:
  - service: input_boolean.toggle
    entity_id: input_boolean.rf_remote_2_on