alias: Rf Remote 2 A
hide_entity: True
trigger:
  platform: mqtt
  topic: "home/OpenMQTTGateway/433toMQTT"
  payload: "2599032"
action:
  - service: input_boolean.toggle
    entity_id: input_boolean.rf_remote_2_a