alias: Rf Remote Bauhn 3 Off
hide_entity: True
trigger:
  platform: mqtt
  topic: "home/OpenMQTTGateway/433toMQTT"
  payload: "349144514"
action:
  - service: input_boolean.toggle
    entity_id: input_boolean.rf_remote_3_off