alias: Rf Remote All On
hide_entity: True
trigger:
  platform: event
  event_type: pilight_received
  event_data:
    protocol: rc101
    id: 127784
    uuid: 0000-b8-27-eb-60df5f   
    state: 'on'
    all: 1
action:
  - service: input_boolean.toggle
    entity_id: input_boolean.rf_remote_all_on