- platform: mjpeg
  name: Front Door Cam
  mjpeg_url: !secret front_door_cam_mjpeg_url
- platform: mjpeg
  name: Ruby Cam
  mjpeg_url: !secret ruby_cam_mjpeg_url
  username: !secret camera_username
  password: !secret camera_password