- platform: owntracks_http
#- platform: bluetooth_tracker
#  interval_seconds: 20
#  track_new_devices: yes
# - platform: tomato
#   host: !secret tomato_host
#   username: !secret tomato_username
#   password: !secret tomato_password
#   http_id: !secret tomato_http_id
#   port: 80
#   ssl: false
#   verify_ssl: false
# - platform: ping
#   hosts:
#     ettiennes_iphone: !secret ettienne_iphone_ip
#     kkramers_iphone: !secret kelly_iphone_ip
