- platform: dcs855l
  host: !secret ruby_cam_host
  name: Ruby Room Temp
  username: !secret camera_username
  password: !secret camera_password
- platform: systemmonitor
  resources: 
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /home
    - type: load_1m
    - type: load_5m
    - type: load_15m
- platform: yr
- platform: time_date
  display_options:
    - 'date_time'
# - platform: bom
#   station: !secret bom_station
#   name: Weather 
#   monitored_conditions:
#     - air_temp
#     - rain_trace
#     - rel_hum
#     - weather
#     - wind_dir
#     - wind_spd_kmh
# - platform: dht
#   name: PI Temp
#   sensor: DHT11
#   pin: 3
#   monitored_conditions:
#     - temperature
#     - humidity
- platform: bh1750
  name: Living Room Light Sensor
  i2c_address: 0x23
  operation_mode: continuous_high_res_mode_1
  multiplier: 10
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
  hour:
    - 0
    - 6
    - 12
    - 18
    - 22
- platform: cert_expiry
  host: !secret cert_expiry_host
  
- platform: mqtt  
  state_topic: "bruh/sensornode1"  
  name: "SN1 Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  
  
- platform: mqtt  
  state_topic: "bruh/sensornode1"  
  name: "SN1 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  

- platform: mqtt  
  state_topic: "bruh/sensornode1"  
  name: "SN1 PIR"  
  value_template: '{{ value_json.motion }}'  

- platform: mqtt  
  state_topic: "bruh/sensornode1"  
  name: "SN1 Temperature"  
  unit_of_measurement: "°F"  
  value_template: '{{ value_json.temperature | round(1) }}'  

- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "SN1 Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'

- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "SN1 Distance"
  unit_of_measurement: "cm"
  value_template: '{{ value_json.distance | round(1) }}'

- platform: google_travel_time
  name: "Time to home"
  api_key: !secret google_assistant_api_key
  origin: device_tracker.ett_iphone
  destination: !secret home_address

- platform: google_travel_time
  name: "Time to work"
  api_key: !secret google_assistant_api_key
  origin: device_tracker.ett_iphone
  destination: !secret work_address